name: CI/CD Frontend Innovatech

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: Build y Push imagen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-innovatech:latest

  deploy:
    name: Deploy en EC2 Frontend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend-innovatech:latest
            docker run -d \
              --name frontend-app \
              --restart unless-stopped \
              -p 80:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/frontend-innovatech:latest
            docker ps | grep frontend-app
            echo "✅ Frontend desplegado OK"
