name: CI/CD Frontend Innovatech ECS

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t frontend-innovatech .

      - name: Tag Docker image
        run: |
          docker tag frontend-innovatech:latest 159773920634.dkr.ecr.us-east-1.amazonaws.com/frontend-innovatech:latest

      - name: Push image to ECR
        run: |
          docker push 159773920634.dkr.ecr.us-east-1.amazonaws.com/frontend-innovatech:latest

      - name: Actualizar ECS
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service frontend-service \
            --force-new-deployment
